[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.8", features = ["derive"] }
indicatif = { version = "0.17.1", features = ["rayon"] }
rand = "0.8.5"
rayon = "1.5.3"
